version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    environment:
      GO111MODULE: "on"

    working_directory: /go/src/github.com/globocom/huskyCI

    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: "Test"
          command: |
            make test
            mv api/coverage.html /tmp/artifacts
      - run:
          name: "Lint"
          command: |
            make lint
      - run:
          name: "Check security"
          command: |
            make check-sec
      - run:
          name: "Goveralls"
          command: |
            $GOPATH/bin/goveralls -coverprofile=c.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_artifacts:
          path: /tmp/artifacts
